language: python
python: 
        - 2.6
services: 
        - redis
install: 
        - pip install redis
        - pip install beautifulsoup4
        - pip install plotly
        - pip install ordereddict
        - pip install simplejson
        
before_script:
        - before_script

script:
        - python waterline.py

branches:
        only:
        - master
