language: python
python: 
        - 2.6
services: 
        - redis 
install: 
        - pip install redis
        - pip install beautifulsoup4
        - pip install plotly
        - pip install ordereddict
        - pip install simplejson

script:
        - python waterline.py

branches:
        only:
        - master
