language: python
python: 
        - 2.6
install: 
        - pip install redis
        - pip install beautifulsoup4
        - pip install plotly
        - pip install ordereddict
        - pip install simplejson

script:
        - python waterline.py
